### ISSUE TITLE
Unpickling error Bu2022Ye.pkl (invalid load key "\x0a")

### ISSUE THREAD

**Issue by haukekoehn** [nuclear-multimessenger-astronomy/nmma#251] opened 2023-09-27 12:10 UTC
**Describe the bug**
When loading the svd models from Bu2022Ye.pkl, the unpickling fails because and returns a warning: pickle.UnpicklingERror: invalid loadkye, '\x0a'. This happens when different protocols are used for pickling and unpickling.

**To Reproduce**
Start a multimessenger analysis with GW, KN and GRB. NMMA current commit.

**Comment by mcoughlin** [comment] 2023-09-27 12:14
@haukekoehn I suspect this a python version issue. Are you on 3.11 perhaps?

**Comment by haukekoehn** [comment] 2023-09-27 12:19
no python 3.8

**Comment by mcoughlin** [comment] 2023-09-27 12:20
@haukekoehn does moving to 3.9 make any difference?

**Comment by haukekoehn** [comment] 2023-09-27 12:41
no

**Comment by mcoughlin** [comment] 2023-09-27 12:43
@sahiljhawar @bfhealy can anyone reproduce?

**Comment by mcoughlin** [comment] 2023-09-27 13:31
@sahiljhawar i was more asking you to confirm if you can load the file.

**Comment by sahiljhawar** [comment] 2023-09-27 13:34
@mcoughlin Ahh okay. Let me check.

**Comment by sahiljhawar** [comment] 2023-09-27 13:37
If `Bu2022Ye.pkl` is same as `Bu2022Ye_tf.pkl` from [Zenodo: 8164628](https://zenodo.org/record/8164628); then yes, I am able to load it using `numpy`

**Comment by mcoughlin** [comment] 2023-09-27 13:41
@haukekoehn Can you download that file separately and check the same?

**Comment by haukekoehn** [comment] 2023-09-27 13:46
I am currently trying to see whether it works on another machine.

But yes, downloading `Bu2022Ye_tf.pkl` and reading it in works. 

So i wanna start a GW+KN+GRB inference from scratch and only provide an empty directory for the svd models. Then it does its thing and starts downloading `Bu2022Ye.pkl` (no tf!). I just looked into this file and it actually looks like an html file, not a binary file.

**Comment by mcoughlin** [comment] 2023-09-27 13:47
Ok so that means maybe the download is failing... maybe lack of Zenodo access for that machine? What's the error?

**Comment by sahiljhawar** [comment] 2023-09-27 13:49
In that case you can get the model from `/home/enlil/jhawar/svdmodels` and start your run with local files

**Comment by haukekoehn** [comment] 2023-09-27 14:01
alright, thanks, i will try!

on the other machine, i get a different error message. There it complains even earlier that "Bu2022Ye_tf" is not in the models list.

**Comment by haukekoehn** [comment] 2023-09-27 14:15
On the other machine it fails even earlier and  raises a ValueError model_name Bu2022Ye_tf not found in models list

**Comment by sahiljhawar** [comment] 2023-09-27 14:20
I think you need `models.yaml` file as well

**Comment by haukekoehn** [comment] 2023-09-28 09:35
I know managed to get it running (or at least initializing the live points :D), but interestingly enough, it only downloaded the models when it was run with a single process, i.e. only nmma-analysis, not srun nmma-analysis. Then the models appeared in the directory and i could restart with srun - n 1024 nmma-analysis.

**Comment by mcoughlin** [comment] 2023-09-28 11:37
@tsunhopang maybe we need a line to check whether the model is there and indicate to first run the download if it isn't and then the user can rerun?

**Comment by sahiljhawar** [comment] 2023-09-28 19:23
@mcoughlin @bfhealy Part of the problem arises from here https://github.com/nuclear-multimessenger-astronomy/nmma/blob/4ba91655a509bce6286574d3c5ad4b764788686c/nmma/em/model.py#L251

Even the tests with `Bu2022Ye` fails ([here](https://github.com/sahiljhawar/nmma/actions/runs/6343223977/job/17230687370))

**Comment by mcoughlin** [comment] 2023-09-28 20:21
@sahiljhawar @bfhealy Maybe it's time to deprecate that pathway?

**Comment by sahiljhawar** [comment] 2023-09-28 21:54
So now, we just need `{model-name}.pkl` and `{model-name_filter}.pkl`, right?

**Comment by bfhealy** [comment] 2023-09-28 21:59
@sahiljhawar That's correct for files on Zenodo! When they get downloaded via NMMA code, the filter-specific files get renamed to `{filter}.pkl` or `{filter}.h5` and put in a model-specific directory.

**Comment by sahiljhawar** [comment] 2023-09-28 22:01
@bfhealy For that, in one of the previous meetings it was finalised that a mirror of Zenodo models will be stored on Potsdam server for faster and easier acess. This was the directory structure can be preserved

**Comment by sahiljhawar** [comment] 2023-09-28 22:06
But in any case, the support for `*_mag.pkl` and `*_lbol.pkl` should be removed, since we do not have those files anymore

**Comment by sahiljhawar** [comment] 2023-09-28 22:09
Also does the `model.pkl` and `filter.h5` (stored inside `model` folder) serve different purpose? Or do they contain same data with different file structure?

**Comment by bfhealy** [comment] 2023-09-28 22:19
They serve different purposes - each `model.pkl` file contains basic SVD information while the `filter.h5` files contain the trained neural network weights/biases mapping merger parameters to light curve eigenvalues (in tensorflow format).

**Closed** 2023-10-04 21:37 UTC
Labels: bug
